# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064876969e8f536f9028d9152a98eba2654ddb6121d2bc9483f7feabd899e958310c415243eade35aaa16472a5fdfc65c248e56421c98e6d711023fca3789d39

test:
  secret_key_base: 32ff6064a4a20d8c1dc1a20d586cbdc2745c3035a12e41ce8afdd5a8f6fbfefa8bcc917ae5c01b6e48f210ea69566180f2ce3549be31012212bc05f083b86ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
